SELECT s.SID
FROM Students s
JOIN Enrollments e ON s.SID = e.SID
JOIN Courses c ON e.CID = c.CID
WHERE c.c_name IN ('EECS442', 'EECS445', 'EECS492', 'EECS482', 'EECS486', 'EECS281')
GROUP BY s.SID
HAVING 
    (COUNT(DISTINCT CASE WHEN c.c_name IN ('EECS442', 'EECS445', 'EECS492') THEN c.CID END) = 3)
    OR 
    (COUNT(DISTINCT CASE WHEN c.c_name IN ('EECS482', 'EECS486') THEN c.CID END) = 2)
    OR
    (COUNT(DISTINCT CASE WHEN c.c_name = 'EECS281' THEN c.CID END) = 1)
ORDER BY s.SID;
